#!/bin/bash

. /etc/docker/modules/outstream.sh
F_JSON=${TEMPLATE_JSON:-"/template.json"}
for row in $(cat "${F_JSON}" | jq -r '.[] | @base64'); do
    _jq() {
     echo ${row} | base64 --decode | jq -r ${1}
    }
   COUNT=$(($COUNT+1))
   template=$(_jq '.template')
   target=$(_jq '.target')
   setLIST=$(_jq '.set[]')
   kvgroup=$(_jq '.keystore.group')
   superkey_command=$(_jq '.keystore.superkey_command')
   if [  "${superkey_command}" = "null" ] && [  "${superkey_command}" = "" ]; then
     superkey_command="hostname"
   fi
   kvsuper="${kvgroup}"".$(${superkey_command})"

   # Copy Templatefile to Target
   DDIR=$(dirname ${target})
   mkdir -p ${DDIR}
   cp -f ${template} ${target}

   # Edit Templatefile and Set VAR_NAME on Placeholder
   for set in $setLIST; do
     if [ "${!set}" = "" ]; then
       if [ ! -z ${REDIS_HOST} ]; then
         info "ENV '$set' not set - try get ENV from keystore ${REDIS_HOST} ${kvsuper} "
         superv=$(clireds ${REDIS_HOST} hget ${kvsuper} ${set})
         if [  "${superv}" = "null" ] && [  "${superv}" = "" ]; then
            info "Another try for ENV '$set' from keystore ${REDIS_HOST} ${kvgroup} "
            export ${set}="$(clireds ${REDIS_HOST} hget ${kvgroup} ${set})"
         else
            info "Setting ENV '$set' from keystore ${REDIS_HOST} ${kvsuper} "
            export ${set}="${superv}"
         fi
       fi
     fi

     if [ "${!set}" = "" ] || [ "${!set}" = "null" ]; then
       error "NO VALUE for $set"
       exit 1;
     fi
       strReplace "${set}" "${!set}" "${target}"
   done
done
