#!/bin/bash

. /etc/docker/modules/outstream.sh
F_JSON=${TEMPLATE_JSON:-"/template.json"}
for row in $(cat "${F_JSON}" | jq -r '.[] | @base64'); do
    _jq() {
     echo ${row} | base64 --decode | jq -r ${1}
    }
   COUNT=$(($COUNT+1))
   template=$(_jq '.template')
   target=$(_jq '.target')
   setLIST=$(_jq '.set[]')
   kvgroup=$(_jq '.keystore.group')

   # Copy Templatefile to Target
   DIR=$(dirname ${target})
   mkdir -p $dirname
   cp -f ${template} ${target}

   # Edit Templatefile and Set VAR_NAME on Placeholder
   for set in $setLIST; do
     if [ "${!set}" = "" ]; then
       if [ ! -z ${REDIS_HOST} ]; then
         debug "ENV '$set' not set - try get ENV from keystore ${REDIS_HOST} ${kvgroup} "
         export ${set}="$(clireds ${REDIS_HOST} hget ${kvgroup} ${set})"
       fi
     fi

     if [ "${!set}" = "" ] || [ "${!set}" = "null" ]; then
       error "NO VALUE for $set"
       exit 1;
     fi
       strReplace "${set}" "${!set}" "${target}"
   done
done
