#!/bin/bash

F_JSON=${TEMPLATE_JSON:-"/template.json"}
for row in $(cat "${F_JSON}" | jq -r '.[] | @base64'); do
    _jq() {
     echo ${row} | base64 --decode | jq -r ${1}
    }
   COUNT=$(($COUNT+1))
   template=$(_jq '.template')
   target=$(_jq '.target')
   setLIST=$(_jq '.set[]')

   # Copy Templatefile to Target
   cp -f ${template} ${target}

   # Edit Templatefile and Set VAR_NAME on Placeholder
   for set in $setLIST; do
     if [ "${!set}" = "" ]; then
       echo "[ERROR] - NO VALUE for $set"
       exit 1;
     fi
       strReplace "${set}" "${!set}" "${target}"
   done
done
